# Generated by Django 3.1.2 on 2021-02-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210228_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={'ordering': ['-scope']},
        ),
    ]
